### ISSUE TITLE
Is it possible to pass my own onScroll to DraxList?

### ISSUE THREAD

**Issue by afgarcia86** [nuclearpasta/react-native-drax#63]
I am trying to replace a `react-native-draggable-flatlist` with this library however they have a `onScrollOffsetChange` prop that allows me to do a parallax effect while scrolling. If I can pass my own onScroll to the `FlatList` I should be able to replicate the same effect. 

example: 
```
onScroll={({ nativeEvent }) => {
    this.state.scrollY.setValue(nativeEvent.contentOffset.y);
}}
```

Alternatively is there a way to use values form the `useDraxRegistry`?

**Comment by lafiosca** [comment]
Off the top of my head, I don’t believe this is currently supported, but it should be relatively easy to add.

**Comment by afgarcia86** [comment]
That was pretty easy https://github.com/nuclearpasta/react-native-drax/pull/64

**Comment by lafiosca** [comment]
Technically I think this is more of a bug than a feature request, since the library intends to allow you to pass all of the underlying `FlatList` props and have them honored. We create our own `onScroll` and currently ignore the prop entirely, even though it is passable to `DraxList`. Either way, we'll add it.
